services:
  db:
    image: mysql:8.0
    container_name: observatorio_db
    restart: always
    environment:
          MYSQL_DATABASE: observatorio_db
          MYSQL_USER: observatorio_user
          MYSQL_PASSWORD: 123456
          MYSQL_ROOT_PASSWORD: password_root_seguro
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: observatorio_web
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    volumes:
      - media_data:/vol/web/media
      - static_data:/vol/web/static
      # Opcionalmente montar el código para live-reloading en desarrollo
      - .:/app:z
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  media_data:
  static_data:
