/**
 * geoData.js - Catálogos geográficos y de juntas auxiliares para la app móvil
 * Observatorio de Datos Huaquechula
 */

export const PAISES_COMUNES = [
    "México",
    "Estados Unidos",
    "Canadá",
    "España",
    "Colombia",
    "Argentina",
    "Francia",
    "Alemania",
    "Reino Unido",
    "Brasil",
    "Chile",
    "Italia",
    "Japón",
    "China",
    "Guatemala",
    "Perú",
    "Costa Rica",
    "Otro país"
];

export const DATOS_MEXICO = {
    "Puebla": [
        "Huaquechula",
        "Puebla de Zaragoza",
        "Atlixco",
        "San Pedro Cholula",
        "San Andrés Cholula",
        "Tehuacán",
        "Izúcar de Matamoros",
        "San Martín Texmelucan",
        "Cuautlancingo",
        "Amozoc",
        "Tepeaca",
        "Zacatlán",
        "Chignahuapan",
        "Huauchinango",
        "Teziutlán",
        "Tochimilco",
        "Atzitzihuacán",
        "Tianguismanalco",
        "Santa Isabel Cholula",
        "San Jerónimo Tecuanipan",
        "Calpan",
        "Chiautla de Tapia",
        "Acatlán de Osorio",
        "Tecamachalco",
        "Libres",
        "Otro municipio de Puebla"
    ],
    "Ciudad de México": [
        "Cuauhtémoc",
        "Coyoacán",
        "Benito Juárez",
        "Miguel Hidalgo",
        "Tlalpan",
        "Álvaro Obregón",
        "Iztapalapa",
        "Gustavo A. Madero",
        "Venustiano Carranza",
        "Azcapotzalco",
        "Xochimilco",
        "Iztacalco",
        "Cuajimalpa",
        "Magdalena Contreras",
        "Tláhuac",
        "Milpa Alta",
        "Otra alcaldía"
    ],
    "Estado de México": [
        "Toluca",
        "Ecatepec",
        "Naucalpan",
        "Tlalnepantla",
        "Nezahualcóyotl",
        "Metepec",
        "Chalco",
        "Valle de Chalco",
        "Chimalhuacán",
        "Ixtapaluca",
        "Texcoco",
        "Atizapán de Zaragoza",
        "Cuautitlán Izcalli",
        "Huixquilucan",
        "Amecameca",
        "Tepotzotlán",
        "Otro municipio del Edo. Mex."
    ],
    "Morelos": [
        "Cuernavaca",
        "Cuautla",
        "Jiutepec",
        "Temixco",
        "Tepoztlán",
        "Yautepec",
        "Jojutla",
        "Emiliano Zapata",
        "Ayala",
        "Yecapixtla",
        "Otro municipio de Morelos"
    ],
    "Tlaxcala": [
        "Tlaxcala de Xicohténcatl",
        "Apizaco",
        "Huamantla",
        "Chiautempan",
        "San Pablo del Monte",
        "Zacatelco",
        "Otro municipio de Tlaxcala"
    ],
    "Veracruz": [
        "Veracruz",
        "Xalapa",
        "Coatzacoalcos",
        "Córdoba",
        "Orizaba",
        "Poza Rica",
        "Boca del Río",
        "Minatitlán",
        "Tuxpan",
        "Papantla",
        "Otro municipio de Veracruz"
    ],
    "Oaxaca": [
        "Oaxaca de Juárez",
        "San Juan Bautista Tuxtepec",
        "Salina Cruz",
        "Juchitán de Zaragoza",
        "Santa Cruz Xoxocotlán",
        "Huajuapan de León",
        "Puerto Escondido",
        "Bahías de Huatulco",
        "Otro municipio de Oaxaca"
    ],
    "Guerrero": [
        "Acapulco de Juárez",
        "Chilpancingo",
        "Iguala de la Independencia",
        "Zihuatanejo",
        "Taxco de Alarcón",
        "Tlapa de Comonfort",
        "Otro municipio de Guerrero"
    ],
    "Hidalgo": [
        "Pachuca de Soto",
        "Tulancingo",
        "Tula de Allende",
        "Mineral de la Reforma",
        "Tizayuca",
        "Huejutla",
        "Otro municipio de Hidalgo"
    ],
    "Jalisco": [
        "Guadalajara",
        "Zapopan",
        "Tlaquepaque",
        "Tonalá",
        "Tlajomulco de Zúñiga",
        "Puerto Vallarta",
        "Lagos de Moreno",
        "Tepatitlán",
        "Otro municipio de Jalisco"
    ],
    "Nuevo León": [
        "Monterrey",
        "San Pedro Garza García",
        "Guadalupe",
        "San Nicolás de los Garza",
        "Apodaca",
        "Santa Catarina",
        "General Escobedo",
        "Santiago",
        "Otro municipio de Nuevo León"
    ],
    "Querétaro": [
        "Santiago de Querétaro",
        "San Juan del Río",
        "Corregidora",
        "El Marqués",
        "Tequisquiapan",
        "Jalpan de Serra",
        "Otro municipio de Querétaro"
    ],
    "Guanajuato": [
        "León",
        "Irapuato",
        "Celaya",
        "Salamanca",
        "Guanajuato",
        "San Miguel de Allende",
        "Silao",
        "Dolores Hidalgo",
        "Otro municipio de Guanajuato"
    ],
    "Michoacán": [
        "Morelia",
        "Uruapan",
        "Zamora",
        "Lázaro Cárdenas",
        "Pátzcuaro",
        "Zitácuaro",
        "Otro municipio de Michoacán"
    ],
    "Aguascalientes": ["Aguascalientes", "Jesús María", "Calvillo", "Rincón de Romos", "Otro municipio"],
    "Baja California": ["Tijuana", "Mexicali", "Ensenada", "Playas de Rosarito", "Tecate", "San Quintín", "Otro municipio"],
    "Baja California Sur": ["La Paz", "Los Cabos", "Cabo San Lucas", "San José del Cabo", "Loreto", "Comondú", "Otro municipio"],
    "Campeche": ["San Francisco de Campeche", "Ciudad del Carmen", "Champotón", "Escárcega", "Calkiní", "Otro municipio"],
    "Chiapas": ["Tuxtla Gutiérrez", "Tapachula", "San Cristóbal de las Casas", "Comitán de Domínguez", "Chiapa de Corzo", "Palenque", "Otro municipio"],
    "Chihuahua": ["Ciudad Juárez", "Chihuahua", "Cuauhtémoc", "Delicias", "Parral", "Nuevo Casas Grandes", "Otro municipio"],
    "Coahuila": ["Saltillo", "Torreón", "Monclova", "Piedras Negras", "Acuña", "Parras de la Fuente", "Otro municipio"],
    "Colima": ["Colima", "Manzanillo", "Villa de Álvarez", "Tecomán", "Otro municipio"],
    "Durango": ["Victoria de Durango", "Gómez Palacio", "Lerdo", "Santiago Papasquiaro", "Otro municipio"],
    "Nayarit": ["Tepic", "Bahía de Banderas", "Compostela", "Santiago Ixcuintla", "San Blas", "Otro municipio"],
    "Quintana Roo": ["Cancún (Benito Juárez)", "Playa del Carmen (Solidaridad)", "Chetumal (Othón P. Blanco)", "Cozumel", "Tulum", "Isla Mujeres", "Otro municipio"],
    "San Luis Potosí": ["San Luis Potosí", "Soledad de Graciano Sánchez", "Ciudad Valles", "Matehuala", "Rioverde", "Tamazunchale", "Otro municipio"],
    "Sinaloa": ["Culiacán", "Mazatlán", "Los Mochis (Ahome)", "Guasave", "Navolato", "Otro municipio"],
    "Sonora": ["Hermosillo", "Ciudad Obregón (Cajeme)", "Nogales", "San Luis Río Colorado", "Navojoa", "Guaymas", "Puerto Peñasco", "Otro municipio"],
    "Tabasco": ["Villahermosa (Centro)", "Cárdenas", "Comalcalco", "Huimanguillo", "Macuspana", "Paraíso", "Otro municipio"],
    "Tamaulipas": ["Reynosa", "Matamoros", "Nuevo Laredo", "Ciudad Victoria", "Tampico", "Ciudad Madero", "Altamira", "Otro municipio"],
    "Yucatán": ["Mérida", "Kanasín", "Valladolid", "Tizimín", "Progreso", "Izamal", "Otro municipio"],
    "Zacatecas": ["Zacatecas", "Guadalupe", "Fresnillo", "Jerez", "Sombrerete", "Otro municipio"]
};

export const JUNTAS_AUXILIARES = [
    { val: "Cabecera Municipal", label: "Cabecera Municipal (Huaquechula Centro)" },
    { val: "Cacaloxúchitl", label: "Cacaloxúchitl" },
    { val: "Mártir Cuauhtémoc", label: "Mártir Cuauhtémoc" },
    { val: "San Antonio Cuautla", label: "San Antonio Cuautla" },
    { val: "San Diego el Organal", label: "San Diego el Organal" },
    { val: "San Juan Huiluco", label: "San Juan Huiluco" },
    { val: "Santa Ana Coatepec", label: "Santa Ana Coatepec" },
    { val: "Santiago Tetla", label: "Santiago Tetla" },
    { val: "Soledad Morelos", label: "Soledad Morelos" },
    { val: "Teacalco de Dorantes", label: "Teacalco de Dorantes" },
    { val: "Tezonteopan de Bonilla", label: "Tezonteopan de Bonilla" },
    { val: "Otra localidad", label: "Otra localidad / comunidad rural" }
];
