"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
from pathlib import Path
import django.db.backends.mysql.base

# Cargar variables de entorno desde .env automáticamente
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR if False else Path(__file__).resolve().parent.parent / '.env')
except ImportError:
    pass  # python-dotenv no instalado; usar variables de entorno del sistema

def check_database_version_supported(self):
    pass




django.db.backends.mysql.base.DatabaseWrapper.check_database_version_supported = check_database_version_supported

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-)xzi6t)9&hsqo5&lzrx3vb(!7=@&h2eyaq9^a)2onl-#5dik%^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/redirigir/'
LOGOUT_REDIRECT_URL = '/login/'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.0.2.2']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'myapp',
    'django.contrib.staticfiles',
    # API Móvil
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Documentación OpenAPI / Swagger
    'drf_spectacular',
    # Utilidades de desarrollo
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS — debe ir primero
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'mysite.urls'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'observatorio'),
        'USER': os.environ.get('DB_USER', 'observatorio_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '123456'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_general_ci',
        }
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', '/vol/web/static')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'myapp/static')]

TEMPLATES[0]['DIRS'] = [os.path.join(BASE_DIR, 'myapp/templates')]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',    # para mantener el backend default (opcional)
]

# Correo SMTP para códigos de verificación 2FA
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')

# Enviar correos reales requiere configurar las variables de entorno SMTP.
# Si quieres forzar esto en desarrollo, define EMAIL_HOST_USER y EMAIL_HOST_PASSWORD.


#prueba 

# settings.py
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', '/vol/web/media')

# Configuración para tipos de archivos permitidos
ALLOWED_EXTENSIONS = {
    'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx',
    'jpg', 'jpeg', 'png', 'gif',
    'mp4', 'avi', 'mov', 'wmv'
}
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB





AUTH_USER_MODEL = 'myapp.Usuario'

# =====================================================
# GOOGLE reCAPTCHA v2
# =====================================================
RECAPTCHA_SITE_KEY   = os.environ.get('RECAPTCHA_SITE_KEY', '6LcENtQsAAAAAOTnhbFqiK-67LfQGtWR3W_KCxaT')
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY', '6LcENtQsAAAAAKCqocNDvvCDqlBirSTPCiQcG9bU')
# INEGI API Configuration
# Obtén tu token registrándote en: https://www.inegi.org.mx/app/api/indicadores/
INEGI_API_TOKEN = '142a3684-a55f-b0d4-b991-26843e97642d'
INEGI_API_BASE_URL = 'https://www.inegi.org.mx/app/api/indicadores/desarrolladores/jsonxml/INDICATOR'
INEGI_API_VERSION = '2.0'
HUAQUECHULA_GEO_CODE = '21071'  # Puebla (21) + Huaquechula (071)

# ============================================
# API REST — Configuración para App Móvil
# ============================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Throttling
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '2000/day',
        'public_api': '500/hour',
    },
    # Documentación OpenAPI
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS — Permitir conexiones desde la app Expo en desarrollo
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8081',
    'http://127.0.0.1:8081',
    'http://10.0.2.2:8081',  # Emulador Android
]
CORS_ALLOW_CREDENTIALS = True

# CORS abierto para endpoints públicos /api/v1/public/
CORS_URLS_REGEX = r'^/api/v1/public/.*$'

# =====================================================
# Swagger / OpenAPI (drf-spectacular)
# =====================================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'Observatorio Territorial de Huaquechula API',
    'DESCRIPTION': (
        'API pública del Observatorio de Datos de Huaquechula. '
        'Datos abiertos bajo licencia CC BY 4.0.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {'email': 'contacto@observatorio-huaquechula.mx'},
    'LICENSE': {'name': 'CC BY 4.0', 'url': 'https://creativecommons.org/licenses/by/4.0/'},
}

# =====================================================
# CORREO ELECTRÓNICO — Recuperación de contraseña
# =====================================================
# Configurar en .env: EMAIL_HOST_USER y EMAIL_HOST_PASSWORD

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST          = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT          = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS       = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'Observatorio Huaquechula <no-reply@observatorio-huaquechula.mx>'
)

# El enlace de reseteo expira en 1 hora (3600 segundos)
PASSWORD_RESET_TIMEOUT = 3600
