# Generated by Django 5.2.7 on 2026-05-21 13:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del proyecto / institución', max_length=100)),
                ('email', models.EmailField(help_text='Correo de contacto del solicitante', max_length=254)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usos_hoy', models.PositiveIntegerField(default=0)),
                ('limite_diario', models.PositiveIntegerField(default=1000)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'APIKey',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='fas fa-folder', max_length=50)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria_Sitio',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_slug', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Sitio',
                'verbose_name_plural': 'Categorías de Sitios',
                'db_table': 'Categoria_Sitio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ap', models.CharField(max_length=100)),
                ('am', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(db_column='contrasenia', max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('admin', 'Admin'), ('encuestador', 'Encuestador'), ('propietario', 'Propietario')], max_length=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('clave_admin', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='ArchivoKMZ',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo_path', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL del archivo')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tamanio', models.BigIntegerField(default=0)),
                ('hash_archivo', models.CharField(blank=True, max_length=64, null=True)),
                ('tipo_archivo', models.CharField(choices=[('kml', 'KML (Archivo geográfico)'), ('kmz', 'KMZ (Archivo comprimido)')], default='kmz', max_length=10)),
                ('procesado', models.BooleanField(default=False)),
                ('error_procesamiento', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('url_disponible', models.BooleanField(default=True, verbose_name='URL disponible')),
                ('ultima_verificacion_url', models.DateTimeField(blank=True, null=True)),
                ('codigo_respuesta_url', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo por URL',
                'verbose_name_plural': 'Archivos por URL',
                'db_table': 'ArchivoKMZ',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('clasificacion', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('confidencial', 'Confidencial')], default='publico', max_length=20)),
                ('tipo', models.CharField(choices=[('reporte', 'Reporte'), ('video', 'Video'), ('historico', 'Documento Histórico')], default='reporte', max_length=20)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('tamaño', models.IntegerField(default=0)),
                ('tipo_archivo', models.CharField(blank=True, max_length=10)),
                ('es_publico', models.BooleanField(default=True)),
                ('descargas', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='myapp.categoria')),
                ('clave_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='myapp.eje')),
            ],
        ),
        migrations.CreateModel(
            name='Encuestador',
            fields=[
                ('clave_encuestador', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='encuestador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Encuestador',
            },
        ),
        migrations.CreateModel(
            name='EncuestaComercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_comercio', models.CharField(choices=[('Hospedaje', 'Hospedaje'), ('Alimentos', 'Alimentos'), ('Artesanía', 'Taller/Artesanía'), ('Guía', 'Guía turístico'), ('Otro', 'Otro')], max_length=50)),
                ('participacion_decisiones', models.PositiveSmallIntegerField(choices=[(1, 'No, decisiones unilaterales'), (2, 'Rara vez'), (3, 'A veces, ciertos grupos'), (4, 'Sí, siempre')], verbose_name='¿Se toma en cuenta a la comunidad local para decisiones turísticas?')),
                ('capacitacion_turistica', models.PositiveSmallIntegerField(choices=[(1, 'No he recibido'), (2, 'Sí, pero insuficientes'), (3, 'Sí, frecuentes y útiles')], verbose_name='¿Ha recibido capacitación para mejorar sus servicios?')),
                ('integracion_turistica', models.PositiveSmallIntegerField(choices=[(1, 'Trabajan de forma aislada'), (2, 'Parcialmente integrados'), (3, 'Muy integrados')], verbose_name='¿Qué tan integrados están los proyectos turísticos locales?')),
                ('encuestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.encuestador')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('edad', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=15)),
                ('barrio_colonia', models.CharField(max_length=100)),
                ('confianza_policia', models.PositiveSmallIntegerField(choices=[(1, '1 - Nula'), (2, '2 - Poca'), (3, '3 - Regular'), (4, '4 - Mucha'), (5, '5 - Total')], verbose_name='Confianza en la policía (1-5)')),
                ('percepcion_inseguridad', models.PositiveSmallIntegerField(choices=[(1, 'Muy inseguro'), (2, 'Inseguro'), (3, 'Neutral'), (4, 'Seguro'), (5, 'Muy seguro')], verbose_name='Percepción de inseguridad')),
                ('tension_festividades', models.PositiveSmallIntegerField(choices=[(1, 'Siempre'), (2, 'Frecuentemente'), (3, 'A veces'), (4, 'Rara vez'), (5, 'Nunca')], verbose_name='¿Siente tensión por exceso de visitantes en festividades?')),
                ('acceso_servicios_festividades', models.PositiveSmallIntegerField(choices=[(1, 'Muy afectado'), (2, 'Moderadamente'), (3, 'Poco'), (4, 'Nada')], verbose_name='¿Se ve afectado su acceso a servicios (agua, tránsito) en festividades?')),
                ('perdida_tradicion', models.PositiveSmallIntegerField(choices=[(1, 'Totalmente de acuerdo'), (2, 'De acuerdo'), (3, 'Neutral'), (4, 'En desacuerdo'), (5, 'Totalmente en desacuerdo')], verbose_name='¿Se está perdiendo el respeto a la tradición por el turismo?')),
                ('calidad_aire', models.PositiveSmallIntegerField(choices=[(1, 'Ha empeorado'), (2, 'Se mantiene igual'), (3, 'Ha mejorado mucho')], verbose_name='Percepción de la calidad del aire')),
                ('gestion_residuos', models.PositiveSmallIntegerField(choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Excelente')], verbose_name='Percepción de la gestión de residuos')),
                ('encuestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.encuestador')),
            ],
        ),
        migrations.CreateModel(
            name='GeometriaEspacial',
            fields=[
                ('id_geometria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('punto', 'Punto'), ('linea', 'Línea'), ('poligono', 'Polígono'), ('multipoligono', 'Multipolígono'), ('multipunto', 'Multipunto')], max_length=20)),
                ('coordenadas', models.JSONField()),
                ('propiedades', models.JSONField(blank=True, null=True)),
                ('estilo', models.JSONField(blank=True, null=True)),
                ('perimetro', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_archivo', models.ForeignKey(blank=True, db_column='id_archivo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.archivokmz')),
            ],
            options={
                'verbose_name': 'Geometría Espacial',
                'verbose_name_plural': 'Geometrías Espaciales',
                'db_table': 'GeometriaEspacial',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50)),
                ('inegi_indicator_id', models.CharField(blank=True, help_text='ID del indicador en la API del INEGI', max_length=50, null=True)),
                ('data_source', models.CharField(choices=[('manual', 'Manual'), ('inegi', 'INEGI'), ('other', 'Otra fuente')], default='manual', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última sincronización con fuente externa', null=True)),
                ('geo_code', models.CharField(default='21071', max_length=10)),
                ('nivel_geografico', models.CharField(blank=True, max_length=50, null=True)),
                ('encuesta_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('encuesta_pregunta', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='myapp.categoriaindicador')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='myapp.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('clave_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_propiedad', models.CharField(blank=True, choices=[('ofrenda', 'Ofrenda'), ('comercio', 'Comercio')], max_length=20, null=True)),
                ('tipo_comercio', models.CharField(blank=True, choices=[('estatico', 'Comercio Estático (Lugar Fijo)'), ('temporal', 'Puesto Temporal (Por temporada)')], max_length=20, null=True)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Propietario',
            },
        ),
        migrations.CreateModel(
            name='Punto_Interes',
            fields=[
                ('id_punto', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('ofrenda', 'Ofrenda'), ('servicio', 'Servicio'), ('sitio_turistico', 'Sitio Turístico'), ('evento', 'Evento'), ('otro', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_portada', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen portada')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('dias_semana', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_geometria', models.ForeignKey(blank=True, db_column='id_geometria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.geometriaespacial')),
                ('propietarios', models.ManyToManyField(blank=True, related_name='puntos_asignados', to='myapp.propietario')),
                ('usuario_creacion', models.ForeignKey(blank=True, db_column='usuario_creacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Interés',
                'verbose_name_plural': 'Puntos de Interés',
                'db_table': 'Punto_Interes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ofrenda',
            fields=[
                ('id_ofrenda', models.AutoField(primary_key=True, serialize=False)),
                ('anfitrion', models.CharField(max_length=100)),
                ('id_punto', models.OneToOneField(db_column='id_punto', on_delete=django.db.models.deletion.CASCADE, to='myapp.punto_interes')),
            ],
            options={
                'verbose_name': 'Ofrenda',
                'verbose_name_plural': 'Ofrendas',
                'db_table': 'Ofrenda',
            },
        ),
        migrations.CreateModel(
            name='Galeria_Multimedia',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('url_archivo', models.URLField(max_length=1000, verbose_name='URL del archivo')),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio')], default='imagen', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_portada', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_punto', models.ForeignKey(db_column='id_punto', on_delete=django.db.models.deletion.CASCADE, to='myapp.punto_interes')),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Galería Multimedia',
                'db_table': 'Galeria_Multimedia',
                'ordering': ['-es_portada', '-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estancia_dias', models.PositiveSmallIntegerField(default=1)),
                ('visitas_previas', models.PositiveSmallIntegerField(default=1)),
                ('motivo_visita', models.CharField(choices=[('turismo', 'Turismo'), ('negocios', 'Negocios'), ('visita_familiar', 'Visita Familiar'), ('estudios', 'Estudios'), ('otros', 'Otros')], default='turismo', max_length=20)),
                ('tipo_transporte', models.CharField(choices=[('automovil', 'Automóvil'), ('autobus', 'Autobús'), ('avion', 'Avión'), ('tren', 'Tren'), ('otros', 'Otros')], default='automovil', max_length=10)),
                ('procedencia', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('es_extranjero', models.BooleanField(default=False)),
                ('mujeres_0_15', models.PositiveSmallIntegerField(default=0)),
                ('mujeres_16_30', models.PositiveSmallIntegerField(default=0)),
                ('mujeres_31_45', models.PositiveSmallIntegerField(default=0)),
                ('mujeres_46_60', models.PositiveSmallIntegerField(default=0)),
                ('mujeres_61_75', models.PositiveSmallIntegerField(default=0)),
                ('mujeres_76_mas', models.PositiveSmallIntegerField(default=0)),
                ('hombres_0_15', models.PositiveSmallIntegerField(default=0)),
                ('hombres_16_30', models.PositiveSmallIntegerField(default=0)),
                ('hombres_31_45', models.PositiveSmallIntegerField(default=0)),
                ('hombres_46_60', models.PositiveSmallIntegerField(default=0)),
                ('hombres_61_75', models.PositiveSmallIntegerField(default=0)),
                ('hombres_76_mas', models.PositiveSmallIntegerField(default=0)),
                ('clave_encuestador', models.ForeignKey(db_column='clave_encuestador', on_delete=django.db.models.deletion.RESTRICT, to='myapp.encuestador')),
            ],
            options={
                'db_table': 'Registro_visita',
            },
        ),
        migrations.CreateModel(
            name='ResenaGlobal',
            fields=[
                ('id_resena', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_visitante', models.CharField(blank=True, max_length=100, null=True)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('oculta', 'Oculta')], default='aprobada', max_length=10)),
                ('modelo_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiqueta de la IA')),
                ('modelo_score', models.FloatField(blank=True, null=True, verbose_name='Certeza de la IA')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('ip_visitante', models.GenericIPAddressField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña Global',
                'verbose_name_plural': 'Reseñas Globales',
                'db_table': 'Resena_Global',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_estimada', models.IntegerField(default=0, help_text='Duración en minutos')),
                ('longitud_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('moderada', 'Moderada'), ('dificil', 'Difícil')], default='moderada', max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('clave_propietario', models.ForeignKey(db_column='clave_propietario', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_geometria', models.ForeignKey(blank=True, db_column='id_geometria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.geometriaespacial')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta_Detalle',
            fields=[
                ('id_ruta_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('tiempo_parada', models.IntegerField(blank=True, help_text='Tiempo en minutos', null=True)),
                ('actividad_sugerida', models.TextField(blank=True, null=True)),
                ('id_punto', models.ForeignKey(db_column='id_punto', on_delete=django.db.models.deletion.CASCADE, to='myapp.punto_interes')),
                ('id_ruta', models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, to='myapp.ruta')),
            ],
            options={
                'verbose_name': 'Detalle de Ruta',
                'verbose_name_plural': 'Detalles de Ruta',
                'db_table': 'Ruta_Detalle',
                'ordering': ['id_ruta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(choices=[('cajero', 'Cajero'), ('hospedaje', 'Hospedaje'), ('modulo', 'Módulo'), ('salud', 'Salud')], default='hospedaje', max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_pago', models.CharField(default='efectivo', max_length=100)),
                ('id_punto', models.OneToOneField(db_column='id_punto', on_delete=django.db.models.deletion.CASCADE, to='myapp.punto_interes')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='Sitio_turistico',
            fields=[
                ('id_sitio', models.AutoField(primary_key=True, serialize=False)),
                ('reglas_acceso', models.TextField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria_sitio')),
                ('id_punto', models.OneToOneField(db_column='id_punto', on_delete=django.db.models.deletion.CASCADE, to='myapp.punto_interes')),
            ],
            options={
                'verbose_name': 'Sitio Turístico',
                'verbose_name_plural': 'Sitios Turísticos',
                'db_table': 'Sitio_turistico',
            },
        ),
        migrations.AddIndex(
            model_name='archivokmz',
            index=models.Index(fields=['usuario', 'tipo_archivo'], name='ArchivoKMZ_usuario_e7a135_idx'),
        ),
        migrations.AddIndex(
            model_name='archivokmz',
            index=models.Index(fields=['visible', 'fecha_subida'], name='ArchivoKMZ_visible_053de3_idx'),
        ),
        migrations.AddIndex(
            model_name='archivokmz',
            index=models.Index(fields=['procesado'], name='ArchivoKMZ_procesa_027134_idx'),
        ),
        migrations.AddIndex(
            model_name='geometriaespacial',
            index=models.Index(fields=['id_archivo', 'tipo'], name='GeometriaEs_id_arch_7a2b15_idx'),
        ),
        migrations.AddIndex(
            model_name='geometriaespacial',
            index=models.Index(fields=['tipo'], name='GeometriaEs_tipo_faa122_idx'),
        ),
        migrations.AddIndex(
            model_name='punto_interes',
            index=models.Index(fields=['categoria', 'estado'], name='Punto_Inter_categor_897ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='punto_interes',
            index=models.Index(fields=['nombre'], name='Punto_Inter_nombre_e3e2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='punto_interes',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='Punto_Inter_fecha_i_b7cfea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ruta_detalle',
            unique_together={('id_ruta', 'orden')},
        ),
    ]
