# Generated by Django 5.2.7 on 2025-12-20 04:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Sitio',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_slug', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Sitio',
                'verbose_name_plural': 'Categorías de Sitios',
                'db_table': 'Categoria_Sitio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Encuestador',
            fields=[
                ('clave_encuestador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Encuestador',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ap', models.CharField(max_length=100)),
                ('am', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(db_column='contrasenia', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipo', models.CharField(choices=[('admin', 'Admin'), ('encuestador', 'Encuestador'), ('propietario', 'Propietario')], max_length=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='ArchivoKMZ',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo_path', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL del archivo')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tamanio', models.BigIntegerField(default=0)),
                ('hash_archivo', models.CharField(blank=True, max_length=64, null=True)),
                ('tipo_archivo', models.CharField(choices=[('kml', 'KML (Archivo geográfico)'), ('kmz', 'KMZ (Archivo comprimido)'), ('imagen', 'Imagen (JPG, PNG, GIF, etc.)'), ('video', 'Video (MP4, AVI, etc.)'), ('audio', 'Audio (MP3, WAV, etc.)'), ('pdf', 'Documento PDF'), ('otro', 'Otro tipo de archivo')], default='kmz', max_length=10)),
                ('procesado', models.BooleanField(default=False)),
                ('error_procesamiento', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('url_disponible', models.BooleanField(default=True, verbose_name='URL disponible')),
                ('ultima_verificacion_url', models.DateTimeField(blank=True, null=True)),
                ('codigo_respuesta_url', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo por URL',
                'verbose_name_plural': 'Archivos por URL',
                'db_table': 'ArchivoKMZ',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, default='')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('clasificacion', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('confidencial', 'Confidencial')], default='publico', max_length=13)),
                ('clave_admin', models.ForeignKey(blank=True, db_column='clave_admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'Documento',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='GeometriaEspacial',
            fields=[
                ('id_geometria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('punto', 'Punto'), ('linea', 'Línea'), ('poligono', 'Polígono'), ('multipoligono', 'Multipolígono'), ('multipunto', 'Multipunto')], max_length=20)),
                ('coordenadas', models.JSONField()),
                ('propiedades', models.JSONField(blank=True, null=True)),
                ('estilo', models.JSONField(blank=True, null=True)),
                ('perimetro', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_archivo', models.ForeignKey(blank=True, db_column='id_archivo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.archivokmz')),
            ],
            options={
                'verbose_name': 'Geometría Espacial',
                'verbose_name_plural': 'Geometrías Espaciales',
                'db_table': 'GeometriaEspacial',
            },
        ),
        migrations.CreateModel(
            name='Punto_Interes',
            fields=[
                ('id_punto', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('ofrenda', 'Ofrenda'), ('servicio', 'Servicio'), ('sitio_turistico', 'Sitio Turístico'), ('evento', 'Evento'), ('otro', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_portada', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen portada')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('dias_semana', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_geometria', models.ForeignKey(blank=True, db_column='id_geometria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.geometriaespacial')),
                ('usuario_creacion', models.ForeignKey(blank=True, db_column='usuario_creacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Interés',
                'verbose_name_plural': 'Puntos de Interés',
                'db_table': 'Punto_Interes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ofrenda',
            fields=[
                ('id_ofrenda', models.AutoField(primary_key=True, serialize=False)),
                ('anfitrion', models.CharField(max_length=100)),
                ('id_punto', models.OneToOneField(db_column='id_punto', on_delete=django.db.models.deletion.CASCADE, to='myapp.punto_interes')),
            ],
            options={
                'verbose_name': 'Ofrenda',
                'verbose_name_plural': 'Ofrendas',
                'db_table': 'Ofrenda',
            },
        ),
        migrations.CreateModel(
            name='Galeria_Multimedia',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('url_archivo', models.URLField(max_length=1000, verbose_name='URL del archivo')),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio')], default='imagen', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_portada', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_punto', models.ForeignKey(db_column='id_punto', on_delete=django.db.models.deletion.CASCADE, to='myapp.punto_interes')),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Galería Multimedia',
                'db_table': 'Galeria_Multimedia',
                'ordering': ['-es_portada', '-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estancia_dias', models.PositiveSmallIntegerField(default=1)),
                ('visitas_previas', models.PositiveSmallIntegerField(default=1)),
                ('motivo_visita', models.CharField(choices=[('turismo', 'Turismo'), ('negocios', 'Negocios'), ('visita_familiar', 'Visita Familiar'), ('estudios', 'Estudios'), ('otros', 'Otros')], default='turismo', max_length=20)),
                ('tipo_transporte', models.CharField(choices=[('automovil', 'Automóvil'), ('autobus', 'Autobús'), ('avion', 'Avión'), ('tren', 'Tren'), ('otros', 'Otros')], default='automovil', max_length=10)),
                ('procedencia', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('es_extranjero', models.BooleanField(default=False)),
                ('mujeres_0_15', models.PositiveSmallIntegerField(default=0)),
                ('mujeres_16_30', models.PositiveSmallIntegerField(default=0)),
                ('mujeres_31_45', models.PositiveSmallIntegerField(default=0)),
                ('mujeres_46_60', models.PositiveSmallIntegerField(default=0)),
                ('mujeres_61_75', models.PositiveSmallIntegerField(default=0)),
                ('mujeres_76_mas', models.PositiveSmallIntegerField(default=0)),
                ('hombres_0_15', models.PositiveSmallIntegerField(default=0)),
                ('hombres_16_30', models.PositiveSmallIntegerField(default=0)),
                ('hombres_31_45', models.PositiveSmallIntegerField(default=0)),
                ('hombres_46_60', models.PositiveSmallIntegerField(default=0)),
                ('hombres_61_75', models.PositiveSmallIntegerField(default=0)),
                ('hombres_76_mas', models.PositiveSmallIntegerField(default=0)),
                ('clave_encuestador', models.ForeignKey(db_column='clave_encuestador', on_delete=django.db.models.deletion.RESTRICT, to='myapp.encuestador')),
            ],
            options={
                'db_table': 'Registro_visita',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_estimada', models.IntegerField(default=0, help_text='Duración en minutos')),
                ('longitud_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('moderada', 'Moderada'), ('dificil', 'Difícil')], default='moderada', max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('clave_propietario', models.ForeignKey(db_column='clave_propietario', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_geometria', models.ForeignKey(blank=True, db_column='id_geometria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.geometriaespacial')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta_Detalle',
            fields=[
                ('id_ruta_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('tiempo_parada', models.IntegerField(blank=True, help_text='Tiempo en minutos', null=True)),
                ('actividad_sugerida', models.TextField(blank=True, null=True)),
                ('id_punto', models.ForeignKey(db_column='id_punto', on_delete=django.db.models.deletion.CASCADE, to='myapp.punto_interes')),
                ('id_ruta', models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, to='myapp.ruta')),
            ],
            options={
                'verbose_name': 'Detalle de Ruta',
                'verbose_name_plural': 'Detalles de Ruta',
                'db_table': 'Ruta_Detalle',
                'ordering': ['id_ruta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(choices=[('cajero', 'Cajero'), ('hospedaje', 'Hospedaje'), ('modulo', 'Módulo'), ('salud', 'Salud'), ('transporte', 'Transporte')], default='hospedaje', max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_pago', models.CharField(default='efectivo', max_length=100)),
                ('id_punto', models.OneToOneField(db_column='id_punto', on_delete=django.db.models.deletion.CASCADE, to='myapp.punto_interes')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='Sitio_turistico',
            fields=[
                ('id_sitio', models.AutoField(primary_key=True, serialize=False)),
                ('reglas_acceso', models.TextField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria_sitio')),
                ('id_punto', models.OneToOneField(db_column='id_punto', on_delete=django.db.models.deletion.CASCADE, to='myapp.punto_interes')),
            ],
            options={
                'verbose_name': 'Sitio Turístico',
                'verbose_name_plural': 'Sitios Turísticos',
                'db_table': 'Sitio_turistico',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('clave_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='myapp.usuario')),
            ],
            options={
                'db_table': 'Propietario',
            },
        ),
        migrations.AddField(
            model_name='encuestador',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='encuestador', to='myapp.usuario'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('clave_admin', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='myapp.usuario')),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
        migrations.AddIndex(
            model_name='archivokmz',
            index=models.Index(fields=['usuario', 'tipo_archivo'], name='ArchivoKMZ_usuario_e7a135_idx'),
        ),
        migrations.AddIndex(
            model_name='archivokmz',
            index=models.Index(fields=['visible', 'fecha_subida'], name='ArchivoKMZ_visible_053de3_idx'),
        ),
        migrations.AddIndex(
            model_name='archivokmz',
            index=models.Index(fields=['procesado'], name='ArchivoKMZ_procesa_027134_idx'),
        ),
        migrations.AddIndex(
            model_name='geometriaespacial',
            index=models.Index(fields=['id_archivo', 'tipo'], name='GeometriaEs_id_arch_7a2b15_idx'),
        ),
        migrations.AddIndex(
            model_name='geometriaespacial',
            index=models.Index(fields=['tipo'], name='GeometriaEs_tipo_faa122_idx'),
        ),
        migrations.AddIndex(
            model_name='punto_interes',
            index=models.Index(fields=['categoria', 'estado'], name='Punto_Inter_categor_897ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='punto_interes',
            index=models.Index(fields=['nombre'], name='Punto_Inter_nombre_e3e2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='punto_interes',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='Punto_Inter_fecha_i_b7cfea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ruta_detalle',
            unique_together={('id_ruta', 'orden')},
        ),
    ]
