# Generated by Django 5.2.7 on 2025-11-21 06:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ap', models.CharField(max_length=50)),
                ('am', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('admin', 'Admin'), ('encuestador', 'Encuestador'), ('propietario', 'Propietario')], max_length=12)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='fas fa-folder', max_length=50)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.usuario')),
                ('clave_admin', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.usuario')),
                ('clave_propietario', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Propietario',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('tamaño', models.IntegerField(default=0)),
                ('tipo_archivo', models.CharField(blank=True, max_length=10)),
                ('es_publico', models.BooleanField(default=True)),
                ('descargas', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='myapp.categoria')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Encuestador',
            fields=[
                ('clave_encuestador', models.CharField(db_column='clave_encuestador', max_length=50, primary_key=True, serialize=False)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='encuestador', to='myapp.usuario')),
            ],
            options={
                'db_table': 'Encuestador',
            },
        ),
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tamanio_grupo', models.PositiveSmallIntegerField(default=1)),
                ('es_extranjero', models.BooleanField(default=False)),
                ('pais_origen', models.CharField(blank=True, max_length=100)),
                ('procedencia', models.CharField(blank=True, max_length=50)),
                ('tipo_transporte', models.CharField(blank=True, choices=[('Automovil', 'Automovil'), ('Autobus', 'Autobus'), ('Avion', 'Avion'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('motivo_visita', models.CharField(blank=True, choices=[('Turismo', 'Turismo'), ('Trabajo', 'Trabajo'), ('Estudios', 'Estudios'), ('Evento', 'Evento'), ('Otro', 'Otro')], max_length=20, null=True)),
                ('estancia_dias', models.PositiveSmallIntegerField(default=1)),
                ('numero_visitas', models.PositiveSmallIntegerField(default=1)),
                ('id_encuestador', models.ForeignKey(db_column='id_encuestador', on_delete=django.db.models.deletion.CASCADE, to='myapp.encuestador')),
            ],
            options={
                'db_table': 'Registro_visita',
            },
        ),
        migrations.CreateModel(
            name='PersonaVisita',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=10)),
                ('id_registro', models.ForeignKey(db_column='id_registro', on_delete=django.db.models.deletion.CASCADE, related_name='personas_visita', to='myapp.registrovisita')),
            ],
            options={
                'db_table': 'Persona_visita',
            },
        ),
    ]
