# Generated by Django 5.2 on 2026-01-20 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registrovisita',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registrovisita',
            name='procedencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='CategoriaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='myapp.eje')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50)),
                ('inegi_indicator_id', models.CharField(blank=True, help_text='ID del indicador en la API del INEGI', max_length=50, null=True)),
                ('data_source', models.CharField(choices=[('manual', 'Manual'), ('inegi', 'INEGI'), ('other', 'Otra fuente')], default='manual', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última sincronización con fuente externa', null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='myapp.categoriaindicador')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='myapp.indicador')),
            ],
        ),
    ]
