# Generated by Django 5.2.7 on 2026-01-20 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_activo_usuario_is_active_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('reporte', 'Reporte'), ('historico', 'Documento Histórico')], default='reporte', max_length=20),
        ),
        migrations.AlterField(
            model_name='punto_interes',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, db_column='usuario_creacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
