# Generated by Django 5.2.7 on 2026-05-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_twofactorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punto_interes',
            name='imagen_portada',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta o URL de imagen portada'),
        ),
    ]
