# Generated by Django 5.2 on 2026-05-11 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_eje_alter_registrovisita_pais_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaComercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_comercio', models.CharField(choices=[('Hospedaje', 'Hospedaje'), ('Alimentos', 'Alimentos'), ('Artesanía', 'Taller/Artesanía'), ('Guía', 'Guía turístico'), ('Otro', 'Otro')], max_length=50)),
                ('participacion_decisiones', models.PositiveSmallIntegerField(choices=[(1, 'No, decisiones unilaterales'), (2, 'Rara vez'), (3, 'A veces, ciertos grupos'), (4, 'Sí, siempre')], verbose_name='¿Se toma en cuenta a la comunidad local para decisiones turísticas?')),
                ('capacitacion_turistica', models.PositiveSmallIntegerField(choices=[(1, 'No he recibido'), (2, 'Sí, pero insuficientes'), (3, 'Sí, frecuentes y útiles')], verbose_name='¿Ha recibido capacitación para mejorar sus servicios?')),
                ('integracion_turistica', models.PositiveSmallIntegerField(choices=[(1, 'Trabajan de forma aislada'), (2, 'Parcialmente integrados'), (3, 'Muy integrados')], verbose_name='¿Qué tan integrados están los proyectos turísticos locales?')),
                ('encuestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.encuestador')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('edad', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=15)),
                ('barrio_colonia', models.CharField(max_length=100)),
                ('confianza_policia', models.PositiveSmallIntegerField(choices=[(1, '1 - Nula'), (2, '2 - Poca'), (3, '3 - Regular'), (4, '4 - Mucha'), (5, '5 - Total')], verbose_name='Confianza en la policía (1-5)')),
                ('percepcion_inseguridad', models.PositiveSmallIntegerField(choices=[(1, 'Muy inseguro'), (2, 'Inseguro'), (3, 'Neutral'), (4, 'Seguro'), (5, 'Muy seguro')], verbose_name='Percepción de inseguridad')),
                ('tension_festividades', models.PositiveSmallIntegerField(choices=[(1, 'Siempre'), (2, 'Frecuentemente'), (3, 'A veces'), (4, 'Rara vez'), (5, 'Nunca')], verbose_name='¿Siente tensión por exceso de visitantes en festividades?')),
                ('acceso_servicios_festividades', models.PositiveSmallIntegerField(choices=[(1, 'Muy afectado'), (2, 'Moderadamente'), (3, 'Poco'), (4, 'Nada')], verbose_name='¿Se ve afectado su acceso a servicios (agua, tránsito) en festividades?')),
                ('perdida_tradicion', models.PositiveSmallIntegerField(choices=[(1, 'Totalmente de acuerdo'), (2, 'De acuerdo'), (3, 'Neutral'), (4, 'En desacuerdo'), (5, 'Totalmente en desacuerdo')], verbose_name='¿Se está perdiendo el respeto a la tradición por el turismo?')),
                ('calidad_aire', models.PositiveSmallIntegerField(choices=[(1, 'Ha empeorado'), (2, 'Se mantiene igual'), (3, 'Ha mejorado mucho')], verbose_name='Percepción de la calidad del aire')),
                ('gestion_residuos', models.PositiveSmallIntegerField(choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Excelente')], verbose_name='Percepción de la gestión de residuos')),
                ('encuestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.encuestador')),
            ],
        ),
    ]
