# Generated by Django 5.2 on 2026-05-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_encuestacomercio_encuestaresidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='geo_code',
            field=models.CharField(default='21071', help_text='Código geográfico de INEGI (ej. 21071 Huaquechula, 21 Puebla, 00 Nacional)', max_length=10),
        ),
    ]
