# Generated by Django 5.2.7 on 2026-05-25 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_punto_interes_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punto_interes',
            name='id_geometria',
            field=models.ForeignKey(blank=True, db_column='id_geometria', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.geometriaespacial'),
        ),
    ]
