# Generated by Django 4.2.27 on 2026-05-01 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_documento_tipo_alter_punto_interes_usuario_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivokmz',
            name='tipo_archivo',
            field=models.CharField(choices=[('kml', 'KML (Archivo geográfico)'), ('kmz', 'KMZ (Archivo comprimido)')], default='kmz', max_length=10),
        ),
        migrations.CreateModel(
            name='ResenaGlobal',
            fields=[
                ('id_resena', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_visitante', models.CharField(blank=True, max_length=100, null=True)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('oculta', 'Oculta')], default='aprobada', max_length=10)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('ip_visitante', models.GenericIPAddressField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña Global',
                'verbose_name_plural': 'Reseñas Globales',
                'db_table': 'Resena_Global',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
