# Generated by Django 5.2 on 2026-05-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_categoria_eje_lugar_documento_categoriaindicador_and_more'),
        ('myapp', '0003_encuestacomercio_encuestaresidente'),
    ]

    operations = [
    ]
