# Generated by Django 5.2 on 2026-05-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_indicador_geo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='nivel_geografico',
            field=models.CharField(choices=[('municipal', 'Municipal'), ('estado', 'Estatal'), ('nacional', 'Nacional')], default='municipal', help_text='Nivel geográfico del indicador: municipal, estatal o nacional', max_length=10),
        ),
    ]
