# Generated by Django 5.2.7 on 2026-05-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_resena_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='tipo_comercio',
            field=models.CharField(blank=True, choices=[('estatico', 'Comercio Estático (Lugar Fijo)'), ('temporal', 'Puesto Temporal (Por temporada)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='tipo_propiedad',
            field=models.CharField(blank=True, choices=[('ofrenda', 'Ofrenda'), ('comercio', 'Comercio')], max_length=20, null=True),
        ),
    ]
