# Generated by Django 3.2.25 on 2025-05-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250524_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestador',
            name='clave_encuestador',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='encuestador',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.usuario'),
        ),
        migrations.AlterField(
            model_name='registrovisita',
            name='id_encuestador',
            field=models.ForeignKey(db_column='id_encuestador', on_delete=django.db.models.deletion.CASCADE, to='myapp.encuestador', to_field='clave_encuestador'),
        ),
    ]
