# Generated by Django 5.2 on 2026-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_encuestacomercio_encuestaresidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('inegi', 'INEGI'), ('other', 'Otra fuente')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='indicador',
            name='inegi_indicator_id',
            field=models.CharField(blank=True, help_text='ID del indicador en la API del INEGI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Última sincronización con fuente externa', null=True),
        ),
    ]
