# Generated by Django 5.2.7 on 2026-05-25 21:25

from django.db import migrations


def cleanup_orphaned_points(apps, schema_editor):
    Punto_Interes = apps.get_model('myapp', 'Punto_Interes')
    Punto_Interes.objects.filter(id_geometria__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_punto_interes_id_geometria'),
    ]

    operations = [
        migrations.RunPython(cleanup_orphaned_points),
    ]
