# Generated by Django 5.2.7 on 2026-05-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_propietario_tipo_comercio_propietario_tipo_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto_interes',
            name='propietarios',
            field=models.ManyToManyField(blank=True, related_name='puntos_asignados', to='myapp.propietario'),
        ),
    ]
