# Generated by Django 5.2 on 2026-05-18 00:55

from django.db import migrations


def create_table_raw(apps, schema_editor):
    """Create the table using raw SQL matching the actual DB schema of Encuestador (int PK, not varchar)."""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Drop if left over from previous failed attempt
            cursor.execute("DROP TABLE IF EXISTS `myapp_encuestavisitante`")
            
            # Create the new table — encuestador_id matches int(11) PK of Encuestador
            cursor.execute("""
                CREATE TABLE `myapp_encuestavisitante` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `fecha` datetime(6) NOT NULL,
                    `genero` varchar(20) NOT NULL,
                    `edad` smallint unsigned NOT NULL,
                    `grupo_viaje` varchar(20) NOT NULL,
                    `ciudad_origen` varchar(100) NOT NULL,
                    `estado_origen` varchar(100) NOT NULL,
                    `pais_origen` varchar(100) NOT NULL DEFAULT 'México',
                    `zonas_visitadas` json NOT NULL,
                    `actividades` json NOT NULL,
                    `calificacion` smallint unsigned NOT NULL,
                    `comentario` longtext NOT NULL,
                    `encuestador_id` int(11) DEFAULT NULL,
                    PRIMARY KEY (`id`),
                    KEY `fk_visitante_enc` (`encuestador_id`),
                    CONSTRAINT `fk_visitante_enc` FOREIGN KEY (`encuestador_id`) REFERENCES `Encuestador` (`clave_encuestador`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
            """)


def drop_table_raw(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS `myapp_encuestavisitante`")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('myapp', '0005_indicador_nivel_geografico'),
    ]

    operations = [
        migrations.RunPython(create_table_raw, drop_table_raw),
    ]
