# Generated by Django 3.2.25 on 2025-05-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250524_0019'),
    ]

    operations = [
    ]
