# Generated by Django 5.2.7 on 2026-05-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_encuestacomercio_encuestaresidente'),
        ('myapp', '0006_punto_interes_propietarios'),
    ]

    operations = [
    ]
