# Generated by Django 3.2.25 on 2025-05-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20250524_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestador',
            name='clave_encuestador',
            field=models.CharField(db_column='clave_encuestador', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encuestador',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='encuestador', to='myapp.usuario'),
        ),
        migrations.AlterField(
            model_name='registrovisita',
            name='id_encuestador',
            field=models.ForeignKey(db_column='id_encuestador', on_delete=django.db.models.deletion.CASCADE, to='myapp.encuestador'),
        ),
        migrations.AlterField(
            model_name='registrovisita',
            name='tipo_transporte',
            field=models.CharField(blank=True, choices=[('Automovil', 'Automovil'), ('Autobus', 'Autobus'), ('Avion', 'Avion'), ('Otro', 'Otro')], max_length=10, null=True),
        ),
    ]
