# Generated by Django 5.2.7 on 2026-05-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_indicador_data_source_indicador_inegi_indicator_id_and_more'),
        ('myapp', '0007_merge_20260515_2201'),
    ]

    operations = [
    ]
