# Generated by Django 3.2.25 on 2025-05-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20250524_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovisita',
            name='estancia_dias',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
