# Generated by Django 5.2.7 on 2026-05-16 05:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_merge_20260515_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='fas fa-folder', max_length=50)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_subida'], 'verbose_name_plural': 'Documentos'},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='clave_admin',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fecha_carga',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='id_documento',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='url',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(default='', upload_to='documentos/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='descargas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documento',
            name='es_publico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='documento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tamaño',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_archivo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registrovisita',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrovisita',
            name='procedencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='documento',
            table=None,
        ),
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='myapp.categoria'),
            preserve_default=False,
        ),
    ]
