# Generated by Django 5.2.7 on 2026-05-18 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_categoria_lugar_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='clasificacion',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('confidencial', 'Confidencial')], default='publico', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='clave_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('reporte', 'Reporte'), ('video', 'Video'), ('historico', 'Documento Histórico')], default='reporte', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='myapp.categoria'),
        ),
    ]
