# Generated by Django 5.2.7 on 2026-05-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_documento_clasificacion_documento_clave_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='encuesta_pregunta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='encuesta_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='nivel_geografico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
