# Generated by Django 5.2 on 2026-05-18 03:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_recreate_encuestainstitucional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestavisitante',
            name='edad',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(127)], verbose_name='¿Cuál es tu edad?'),
        ),
    ]
