# Generated by Django 5.2 on 2026-05-18 03:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_encuestavisitante_edad_encuestainstitucional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestaresidente',
            name='edad',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(127)], verbose_name='Edad'),
        ),
    ]
