# Generated by Django 5.2.7 on 2026-05-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_indicador_encuesta_pregunta_indicador_encuesta_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='geo_code',
            field=models.CharField(default='21071', max_length=10),
        ),
    ]
