# Generated by Django 5.2.7 on 2026-05-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_indicador_geo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del proyecto / institución', max_length=100)),
                ('email', models.EmailField(help_text='Correo de contacto del solicitante', max_length=254)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usos_hoy', models.PositiveIntegerField(default=0)),
                ('limite_diario', models.PositiveIntegerField(default=1000)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'APIKey',
                'ordering': ['-creada'],
            },
        ),
    ]
