# Generated by Django 5.2 on 2026-05-18 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_encuestaresidente_edad_encuestainstitucional_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='EncuestaInstitucional',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('fecha', models.DateTimeField(auto_now_add=True)),
                        ('registro_pci', models.PositiveSmallIntegerField(choices=[(1, 'Sí, contamos con herramientas de monitoreo e inventarios sistemáticos'), (2, 'Se realizan registros eventuales (fotografías o bitácoras de eventos), pero sin un sistema formal'), (3, 'No se cuenta con herramientas institucionales de seguimiento')], verbose_name='1. ¿Cuenta la administración municipal actual con registros, inventarios actualizados o indicadores formales para dar seguimiento periódico al estado de conservación del Patrimonio Cultural Inmaterial (PCI) del municipio?')),
                        ('canales_difusion', models.JSONField(blank=True, default=list, verbose_name='2. ¿Cuáles son los canales oficiales y mecanismos institucionales implementados en el último año para la difusión nacional e internacional del PCI de Huaquechula?')),
                        ('mecanismos_regulacion', models.PositiveSmallIntegerField(choices=[(1, 'Reglamento de turismo vigente que incluye normativas de protección local y ordenamiento comercial'), (2, 'Normas básicas de comercio, pero sin un reglamento específico orientado a la protección cultural'), (3, 'No existen herramientas de regulación turística vigentes')], verbose_name='3. ¿Qué mecanismos normativos o reglamentos locales posee el ayuntamiento para regular el flujo turístico, evitar la saturación de los espacios públicos y proteger los derechos de los artesanos y portadores de identidad?')),
                        ('plan_desarrollo', models.PositiveSmallIntegerField(choices=[(1, 'Sí, se cuenta con un Plan Sectorial alineado a la gestión comunitaria'), (2, 'Existe un plan de desarrollo general, pero carece de un enfoque específico en turismo comunitario'), (3, 'No se cuenta con herramientas de planeación técnica o estratégica en turismo')], verbose_name='4. ¿Dispone el municipio de un Plan de Desarrollo Turístico Municipal u otras herramientas de gestión técnica que prioricen la participación social de las comunidades rurales anfitrionas?')),
                        ('porcentaje_comunidades', models.PositiveSmallIntegerField(choices=[(1, 'Menos del 25% de las localidades (La actividad se centraliza casi por completo en la cabecera municipal)'), (2, 'Entre el 25% y el 50% de las localidades están integradas'), (3, 'Más del 50% de las localidades rurales participan activamente en las redes de turismo municipal')], verbose_name='5. ¿Qué porcentaje de las comunidades rurales con vocación turística del municipio están integradas activamente en los corredores o proyectos turísticos oficiales promovidos por el ayuntamiento?')),
                        ('encuestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.encuestador')),
                    ],
                ),
                migrations.DeleteModel(
                    name='EncuestaComercio',
                ),
            ],
            database_operations=[]
        ),
        migrations.AddField(
            model_name='encuestainstitucional',
            name='visitantes_ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de visitantes registrados al municipio durante el año'),
        ),
        migrations.AddField(
            model_name='encuestainstitucional',
            name='visitantes_tradicion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de visitantes registrados al municipio durante la tradición'),
        ),
    ]
