# Generated by Django 5.2 on 2026-05-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_encuestainstitucional_delete_encuestacomercio'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestaresidente',
            name='interes_jovenes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sí, de forma activa: Existe un fuerte interés y los jóvenes participan activamente en el aprendizaje y preservación de la tradición.'), (2, 'Parcialmente: Conocen las tradiciones y participan en las festividades, pero se está perdiendo la enseñanza de las técnicas o significados profundos.'), (3, 'No, se está perdiendo: Debido a la migración u otros factores, los jóvenes ya no están aprendiendo estos saberes comunitarios.')], null=True, verbose_name='8. En su hogar o entorno cercano, ¿las generaciones más jóvenes (niños y jóvenes) muestran interés y están aprendiendo activamente los saberes, técnicas y significados de nuestras tradiciones (como la elaboración de altares, artesanías o cocina tradicional)?'),
        ),
    ]
