# Generated by Django 5.2.7 on 2026-05-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_add_apikey_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenaglobal',
            name='modelo_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiqueta de la IA'),
        ),
        migrations.AddField(
            model_name='resenaglobal',
            name='modelo_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Certeza de la IA'),
        ),
    ]
