# Generated by Django 5.2 on 2026-05-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_encuestaresidente_interes_jovenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='encuesta_pregunta',
            field=models.CharField(blank=True, help_text='Pregunta(s) específica(s) de la encuesta', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='encuesta_tipo',
            field=models.CharField(blank=True, choices=[('institucional', 'Institucional'), ('visitante', 'Visitante/Turista')], help_text='Tipo de encuesta que alimenta el indicador', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('inegi', 'INEGI'), ('encuesta', 'Encuesta'), ('other', 'Otra fuente')], default='manual', max_length=20),
        ),
    ]
