# Generated by Django 5.2 on 2026-05-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_indicador_encuesta_pregunta_indicador_encuesta_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='encuesta_tipo',
            field=models.CharField(blank=True, choices=[('institucional', 'Institucional'), ('visitante', 'Visitante/Turista'), ('residente', 'Residente')], help_text='Tipo de encuesta que alimenta el indicador', max_length=50, null=True),
        ),
    ]
