# Generated by Django 5.2.7 on 2026-05-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cleanup_orphaned_points'),
    ]

    operations = [
    ]
