# Generated by Django 5.2.7 on 2026-05-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_categoria_lugar_alter_documento_options_and_more'),
        ('myapp', '0016_alter_indicador_encuesta_tipo'),
    ]

    operations = [
    ]
