# Generated by Django 5.2.7 on 2026-05-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_merge_20260518_0711'),
    ]

    operations = [
    ]
