# Generated by Django 5.2.7 on 2026-06-10 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_merge_20260518_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Encuesta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa / Recibiendo Respuestas')),
                ('anonima', models.BooleanField(default=True, verbose_name='Permitir respuestas anónimas')),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'Encuesta',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto de la Pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('TEXTO', 'Texto Corto'), ('PARRAFO', 'Párrafo / Texto Largo'), ('OPCION_MULTIPLE', 'Opción Múltiple (Una sola respuesta)'), ('CASILLAS', 'Casillas de Verificación (Múltiples respuestas)'), ('DESPLEGABLE', 'Lista Desplegable')], default='TEXTO', max_length=20, verbose_name='Tipo de Pregunta')),
                ('requerida', models.BooleanField(default=False, verbose_name='Obligatoria')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='myapp.encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'Pregunta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto de la Opción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='myapp.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Pregunta',
                'verbose_name_plural': 'Opciones de Pregunta',
                'db_table': 'OpcionPregunta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_recibidas', to='myapp.encuesta')),
                ('usuario_responde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que responde')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuesta',
                'db_table': 'RespuestaEncuesta',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True, verbose_name='Valor de la Respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pregunta')),
                ('respuesta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='myapp.respuestaencuesta')),
            ],
            options={
                'verbose_name': 'Respuesta de Pregunta',
                'verbose_name_plural': 'Respuestas de Preguntas',
                'db_table': 'RespuestaPregunta',
            },
        ),
    ]
