# Generated by Django 5.2.7 on 2026-06-29 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_encuesta_pregunta_opcionpregunta_respuestaencuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestaresidente',
            name='beneficio_economico',
            field=models.CharField(blank=True, choices=[('principal', 'Sí, es nuestra fuente de ingresos principal'), ('complementaria', 'Sí, funciona como una actividad económica complementaria'), ('ninguno', 'No, no percibimos ningún beneficio directo de la actividad turística')], max_length=20, null=True, verbose_name='Beneficio económico o social'),
        ),
        migrations.AddField(
            model_name='encuestaresidente',
            name='capacitacion_turistica',
            field=models.CharField(blank=True, choices=[('continua', 'Sí, he recibido capacitación continua'), ('aislada', 'Recibí información aislada, pero no capacitación formal'), ('ninguna', 'No he recibido ninguna información ni capacitación')], max_length=20, null=True, verbose_name='Capacitación turística'),
        ),
        migrations.AddField(
            model_name='encuestaresidente',
            name='interes_jovenes',
            field=models.CharField(blank=True, choices=[('activa', 'Sí, de forma activa'), ('parcialmente', 'Parcialmente'), ('perdiendo', 'No, se está perdiendo')], max_length=20, null=True, verbose_name='Interés de jóvenes en tradiciones'),
        ),
        migrations.AddField(
            model_name='encuestaresidente',
            name='participacion_decisiones',
            field=models.CharField(blank=True, choices=[('regular', 'Sí, asisto con regularidad y se toman en cuenta mis opiniones'), ('no_toman_cuenta', 'He sido convocado, pero no asisto o no se toman en cuenta las opiniones comunitarias'), ('nunca', 'Nunca he sido convocado ni informado sobre estas decisiones')], max_length=20, null=True, verbose_name='Participación en toma de decisiones'),
        ),
        migrations.AddField(
            model_name='encuestaresidente',
            name='participacion_preservacion',
            field=models.CharField(blank=True, choices=[('activa', 'Sí, participo activamente de manera directa'), ('apoyo', 'No participo directamente, pero apoyo la organización local'), ('ninguna', 'No participo en absoluto')], max_length=20, null=True, verbose_name='Participación en preservación'),
        ),
        migrations.AlterField(
            model_name='encuestaresidente',
            name='acceso_servicios_festividades',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Excelente'), (2, 'Regular'), (3, 'Deficiente')], null=True, verbose_name='¿Se ve afectado su acceso a servicios (agua, tránsito) en festividades?'),
        ),
        migrations.AlterField(
            model_name='encuestaresidente',
            name='barrio_colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encuestaresidente',
            name='calidad_aire',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ha empeorado'), (2, 'Se mantiene igual'), (3, 'Ha mejorado mucho')], null=True, verbose_name='Percepción de la calidad del aire'),
        ),
        migrations.AlterField(
            model_name='encuestaresidente',
            name='confianza_policia',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Nula'), (2, '2 - Poca'), (3, '3 - Regular'), (4, '4 - Mucha'), (5, '5 - Total')], null=True, verbose_name='Confianza en la policía (1-5)'),
        ),
        migrations.AlterField(
            model_name='encuestaresidente',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuestaresidente',
            name='genero',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='encuestaresidente',
            name='gestion_residuos',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Excelente')], null=True, verbose_name='Percepción de la gestión de residuos'),
        ),
        migrations.AlterField(
            model_name='encuestaresidente',
            name='percepcion_inseguridad',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Muy inseguro'), (2, 'Inseguro'), (3, 'Neutral'), (4, 'Seguro'), (5, 'Muy seguro')], null=True, verbose_name='Percepción de inseguridad'),
        ),
        migrations.AlterField(
            model_name='encuestaresidente',
            name='perdida_tradicion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sí, se ha comercializado excesivamente'), (2, 'Parcialmente'), (3, 'No, se mantiene intacta')], null=True, verbose_name='¿Se está perdiendo el respeto a la tradición por el turismo?'),
        ),
        migrations.AlterField(
            model_name='encuestaresidente',
            name='tension_festividades',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. No altera nada'), (2, '2. Altera poco'), (3, '3. Altera de forma regular'), (4, '4. Altera mucho')], null=True, verbose_name='¿Siente tensión por exceso de visitantes en festividades?'),
        ),
        migrations.CreateModel(
            name='EncuestaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('seguimiento_salvaguardia', models.CharField(choices=[('si', 'Sí, contamos con herramientas de monitoreo e inventarios sistemáticos'), ('eventual', 'Se realizan registros eventuales (fotografías o bitácoras de eventos), pero sin un sistema formal'), ('no', 'No se cuenta con herramientas institucionales de seguimiento')], max_length=20)),
                ('canales_difusion', models.TextField(help_text='Canales de difusión separados por comas')),
                ('visitantes_festividades', models.PositiveIntegerField()),
                ('regulacion', models.CharField(choices=[('reglamento', 'Reglamento de turismo vigente que incluye normativas de protección local y ordenamiento comercial'), ('normas_basicas', 'Normas básicas de comercio, pero sin un reglamento específico orientado a la protección cultural'), ('no', 'No existen herramientas de regulación turística vigentes')], max_length=20)),
                ('gestion_tecnica', models.CharField(choices=[('si', 'Sí, se cuenta con un Plan Sectorial alineado a la gestión comunitaria'), ('general', 'Existe un plan de desarrollo general, pero carece de un enfoque específico en turismo comunitario'), ('no', 'No se cuenta con herramientas de planeación técnica o estratégica en turismo')], max_length=20)),
                ('integracion_territorial', models.CharField(choices=[('menos_25', 'Menos del 25% de las localidades (La actividad se centraliza casi por completo en la cabecera municipal)'), ('entre_25_50', 'Entre el 25% y el 50% de las localidades están integradas'), ('mas_50', 'Más del 50% de las localidades rurales participan activamente en las redes de turismo municipal')], max_length=20)),
                ('visitantes_anual', models.PositiveIntegerField()),
                ('encuestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.encuestador')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('No binario / Otro', 'No binario / Otro'), ('Prefiero no decirlo', 'Prefiero no decirlo')], max_length=30)),
                ('edad', models.PositiveSmallIntegerField()),
                ('viaja_con', models.CharField(choices=[('Solo / Sola', 'Solo / Sola'), ('En pareja', 'En pareja'), ('En familia (con niños)', 'En familia (con niños)'), ('Con amigos / familiares (adultos)', 'Con amigos / familiares (adultos)'), ('Grupo organizado / Excursión', 'Grupo organizado / Excursión')], max_length=50)),
                ('residencia_ciudad', models.CharField(max_length=100)),
                ('residencia_estado', models.CharField(max_length=100)),
                ('residencia_pais', models.CharField(max_length=100)),
                ('zonas_visitadas', models.TextField(help_text='Zonas visitadas separadas por comas')),
                ('actividades', models.TextField(help_text='Actividades realizadas separadas por comas')),
                ('satisfaccion', models.PositiveSmallIntegerField(choices=[(1, '⭐ Muy mala'), (2, '⭐⭐ Mala'), (3, '⭐⭐⭐ Regular'), (4, '⭐⭐⭐⭐ Buena'), (5, '⭐⭐⭐⭐⭐ Excelente')])),
                ('lo_que_mas_gusto', models.TextField(blank=True, null=True)),
                ('encuestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.encuestador')),
            ],
        ),
    ]
