# Generated by Django 5.2.7 on 2026-09-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_ensure_survey_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestaresidente',
            name='genero',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro'), ('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('No binario / Otro', 'No binario / Otro'), ('Prefiero no decirlo', 'Prefiero no decirlo')], max_length=30, null=True),
        ),
    ]
