# Generated by Django 5.2.7 on 2026-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_encuestaresidente_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIngestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingesta', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_captura_local', models.DateTimeField(blank=True, help_text='Timestamp local del dispositivo móvil', null=True)),
                ('tipo_encuesta', models.CharField(choices=[('visitante', 'Perfil del Visitante'), ('residente', 'Residente Local'), ('institucional', 'Institucional'), ('comercio', 'Comercio Local'), ('dinamica', 'Encuesta Personalizada')], db_index=True, max_length=30)),
                ('id_encuesta', models.PositiveIntegerField(blank=True, null=True)),
                ('encuestador_username', models.CharField(default='anonimo', max_length=100)),
                ('barrio_localidad', models.CharField(blank=True, default='', max_length=150)),
                ('lag_segundos', models.FloatField(default=0.0, help_text='Diferencia en segundos entre captura y recepción en la nube')),
                ('es_offline', models.BooleanField(default=False, help_text='True si fue transmitida con rezago por falta de red')),
                ('latencia_db_ms', models.FloatField(default=0.0)),
                ('estado', models.CharField(default='EXITOSO', max_length=20)),
            ],
            options={
                'verbose_name': 'Registro de Ingesta de Encuesta',
                'verbose_name_plural': 'Registros de Ingesta de Encuestas',
                'db_table': 'RegistroIngestaEncuesta',
                'ordering': ['-fecha_ingesta'],
            },
        ),
    ]
