# Generated by Django 5.2.7 on 2026-09-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_registroingestaencuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='encuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_reporte', to='myapp.encuesta', verbose_name='Encuesta asociada'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='disponible_movil',
            field=models.BooleanField(default=True, verbose_name='Habilitada en App Móvil'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='disponible_web',
            field=models.BooleanField(default=True, verbose_name='Habilitada en Portal Web'),
        ),
    ]
