# Generated by Django 5.2.7 on 2026-09-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_documento_encuesta_encuesta_disponible_movil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestaresidente',
            name='region_origen',
            field=models.CharField(blank=True, choices=[('Cabecera Municipal', 'Cabecera Municipal (Huaquechula Centro)'), ('Cacaloxúchitl', 'Cacaloxúchitl'), ('Mártir Cuauhtémoc', 'Mártir Cuauhtémoc'), ('San Antonio Cuautla', 'San Antonio Cuautla'), ('San Diego el Organal', 'San Diego el Organal'), ('San Juan Huiluco', 'San Juan Huiluco'), ('Santa Ana Coatepec', 'Santa Ana Coatepec'), ('Santiago Tetla', 'Santiago Tetla'), ('Soledad Morelos', 'Soledad Morelos'), ('Teacalco de Dorantes', 'Teacalco de Dorantes'), ('Tezonteopan de Bonilla', 'Tezonteopan de Bonilla'), ('Otra localidad', 'Otra localidad / inspectoría rural')], max_length=100, null=True, verbose_name='Comunidad o Junta Auxiliar de origen'),
        ),
    ]
